# Generated by Django 4.1 on 2022-08-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityclasses',
            name='school_location',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
